env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
# - jest
  - '@typescript-eslint'
rules:
  jsx-a11y/anchor-is-valid: 0
  no-unused-vars:
    - 2
    - argsIgnorePattern: '^_'
