version: '3'
services:
  bot:
    container_name: piyodore
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_BOT_CLIENT_ID=${DISCORD_BOT_CLIENT_ID}
      - DISCORD_BOT_GUILD_ID=${DISCORD_BOT_GUILD_ID}
    tty: true
